### ISSUE TITLE
[Magento 1] Observer.php getBlock called search.result

### ISSUE THREAD

**Issue by karbowiak** [Metrilo/Magento-Plugin#27] opened 2019-02-14 13:59 UTC
Hello there!

I just put this on a site, and then went to use the search function, but got greeted by a blank page - fast forward to some debugging and the culprit was found.

app/code/community/Metrilo/Analytics/Model/Observer.php
line 61
`$resultCount = Mage::app()->getLayout()->getBlock('search.result')->getResultCount();`

If changed to:
```
$block = Mage::app()->getLayout()->getBlock('search.result');
if($block == false)
    return;

$resultCount = Mage::app()->getLayout()->getBlock('search.result')->getResultCount();
```

It is fixed, because the search.result block doesn't always exist on all sites, atleast not in my case :)
If wanted i can make a pull request with the change.

**Comment by IbrahimS2** [comment] 2019-05-03 02:11
@nedick007 @karbowiak That is the downside we get from Metrilo, no serious attention when it comes to development whatsoever.

I had an issue where it is not syncing orders from one of my client's store, they could not resolve it even with full access!

I hope this comment will wake them up!

**Comment by nedick007** [comment] 2019-05-14 13:07
Based on the issue information provided by @karbowiak some systems can experience a missing block Mage::app()>getLayout()>getBlock('search.result') for the catalogsearch_result_index and this resulting in a blank page because of the error thrown in the background. His solution however, is just checking for that block and if it's not present skips the logic of $helper->addEvent('track', 'search', $params) event tracking. The result will be inability to track the search results of the given website.

The problem itself, in my opinion, is caused by a theme or other frontend modification of the core Magento functionality that modifies or rewrites/replaces completely the getBlock('search.result').

I don't believe there is all-in-one solution to the described problem, because we cannot really account for all possible scenarios provided by the ability to extend or modify the Magento core. At some point we will have to rely on the awareness of the project developer and his ability to debug and adapt our integration to the specifics of the project.

That said we believe it is a better solution to replace the missing block with your block of use, for example: $resultCount = Mage::app()->getLayout()->getBlock('YOUR.BLOCK')->getResultCount();
This will fix the blank page error from the missing block and also it will allow us to actually track the results from the search action.

**Closed as completed** 2019-07-01 13:19 UTC
